import { createBrowserRouter } from "react-router-dom";
import App from "../../App";

export const Allroutes = createBrowserRouter([
    {
        path:'',
        element:<App/>
    },
    {
        path:'/DashBoard/',
        element:<App/>
    },
    {
        path:'/studrnts',
        element:<App/>
    },
    {
        path:'/studrnts/AddStudents',
        element:<App/>
    },
    {
        path:'/studrnts/StudentsList',
        element:<App/>
    },
    {
        path:'/Teachers',
        element:<App/>
    },
    {
        path:'/Teachers/AddTeachers',
        element:<App/>
    },
    {
        path:'/Teachers/TeachersList',
        element:<App/>
    },
    {
        path:'/Subjects',
        element:<App/>
    },
    {
        path:'/Subjects/AddSubjects',
        element:<App/>
    },
    {
        path:'/Subjects/SubjectList',
        element:<App/>
    },
    {
        path:'/Attandence',
        element:<App/>
    },
    {
        path:'/Attandence/StudentsAttendence',
        element:<App/>
    },
    {
        path:'/Syllabus',
        element:<App/>
    },
    {
        path:'/Syllabus/SyllabusForm',
        element:<App/>
    },
    {
        path:'/Exames',
        element:<App/>
    },
    {
        path:'/Exames/ScheduleForm',
        element:<App/>
    },
    {
        path:'/Exames/ScheduleList',
        element:<App/>
    },
    {
        path:'/studrnts/StudentsList/:name',
        element:<App/>
    },
    {
        path:'/Teachers/TeachersList/:name',
        element:<App/>
    },
    {
        path:'/Attandence/TeachersAttendence',
        element:<App/>
    },
    {
        path:'/Attandence/AttendenceDetailsPage',
        element:<App/>
    },
    {
        path:'/Acedimic',
        element:<App/>
    },
    {
        path:'/Acedimic/TeachersElocation/List',
        element:<App/>
    },
    {
        path:'/Acedimic/TeachersElocation',
        element:<App/>
    },
    
])